event_management/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
from core.views import home,no_permission
from events.views import EventListView
from django.views.generic import TemplateView 
from debug_toolbar.toolbar import  debug_toolbar_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name="home"),
    # path("cores/", include("core.urls")),
    path("events/", include("events.urls")),
    path('', EventListView.as_view(), name='home'),
    path("users/", include("users.urls",namespace="users")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('no-permission/', TemplateView.as_view(template_name="no_permission.html"), name='no-permission'),
]+ debug_toolbar_urls()
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views
from users.views import (
    SignUpView, CustomLoginView, SignOutView, activate_user,
    AdminDashboardView, AssignRoleView, CreateGroupView,
    GroupListView, ProfileView, EditProfileView,
    ChangePasswordReset, CustomPasswordResetView,
    CustomPasswordResetConfirmView,
)
app_name = 'users'
urlpatterns = [
    path('sign-up/', SignUpView.as_view(), name='sign-up'),
    path('sign-in/', CustomLoginView.as_view(), name='sign-in'),
    path('sign-out/', SignOutView.as_view(), name='sign-out'),

    # Account activation URL with user_id and token parameters
    path('activate/<int:user_id>/<str:token>/', activate_user, name='activate-user'),

    # Admin dashboard and management URLs
    path('dashboard/', AdminDashboardView.as_view(), name='admin_dashboard'),
    path('assign-role/<int:user_id>/', AssignRoleView.as_view(), name='assign-role'),
    path('create-group/', CreateGroupView.as_view(), name='create-group'),
    path('group-list/', GroupListView.as_view(), name='group-list'),

    # User profile URLs
    path('profile/', ProfileView.as_view(), name='profile'),
    path('edit-profile/', EditProfileView.as_view(), name='edit_profile'),

    # Password management
    path('password/change/', ChangePasswordReset.as_view(), name='password_change'),
    path('password/reset/', CustomPasswordResetView.as_view(), name='password_reset'),
    path('password/reset/confirm/<uidb64>/<token>/', CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class CustomUser(AbstractUser):
   
    profile_image = models.ImageField(upload_to='profile_img/', blank=True, null=True)
    phone = models.CharField(max_length=15, blank=True, null=True)

    def __str__(self):
        return self.username

users/forms.py
from django import forms
from django.contrib.auth.forms import (
    UserCreationForm, AuthenticationForm, PasswordChangeForm,
    PasswordResetForm, SetPasswordForm
)
from django.contrib.auth.models import Group
from django.contrib.auth import get_user_model
from users.models import CustomUser  

User = get_user_model()

# Sign Up Form
class CustomRegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name']

# Login Form
class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Username', 'class': 'input input-bordered w-full'
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Password', 'class': 'input input-bordered w-full'
    }))

# Role Assignment Form
class AssignRoleForm(forms.Form):
    role = forms.ModelChoiceField(queryset=Group.objects.all(), empty_label="Select a role")

# Group Creation Form
class CreateGroupForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = ['name']

# Edit Profile Form
class EditProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'profile_image','phone']  

# Password Change Form
class CustomPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'input input-bordered w-full'}))
    new_password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'input input-bordered w-full'}))
    new_password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'input input-bordered w-full'}))

# Password Reset Form (Forgot Password)
class CustomPasswordResetForm(PasswordResetForm):
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'input input-bordered w-full'}))

# Set New Password (After Email Link)
class CustomPasswordResetConfirmForm(SetPasswordForm):
    new_password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'input input-bordered w-full'}))
    new_password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'input input-bordered w-full'}))

users/views.py
from django.contrib.auth import login, logout
from django.contrib.auth.views import LoginView, LogoutView,PasswordChangeView, PasswordResetView, PasswordResetConfirmView
from django.urls import reverse_lazy
from django.shortcuts import redirect, render, get_object_or_404
from django.views import View
from django.views.generic import TemplateView, FormView, UpdateView, ListView
from django.contrib import messages
from django.contrib.auth.models import Group
from django.contrib.auth.tokens import default_token_generator
from django.utils.http import urlsafe_base64_decode
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import get_user_model
from users.forms import (
    CustomRegistrationForm, LoginForm, AssignRoleForm,
    CreateGroupForm, CustomPasswordChangeForm,
    CustomPasswordResetForm, CustomPasswordResetConfirmForm, EditProfileForm
)




User = get_user_model()

# Sign Up View
class SignUpView(FormView):
    template_name = 'users/sign_up.html'
    form_class = CustomRegistrationForm
    success_url = reverse_lazy('sign-in')

    def form_valid(self, form):
        user = form.save(commit=False)
        user.set_password(form.cleaned_data['password1'])
        user.is_active = False 
        user.save()
        messages.success(self.request, 'Account created. Please check your email to activate your account.')
        return super().form_valid(form)

# Custom Login View
class CustomLoginView(LoginView):
    form_class = LoginForm
    template_name = 'registration/login.html'
    authentication_form = LoginForm
    
class SignOutView(LoginRequiredMixin, LogoutView):
    next_page = reverse_lazy('login') 

# Activate User View
def activate_user(request, user_id, token):
    user = get_object_or_404(User, pk=user_id)
    if default_token_generator.check_token(user, token):
        user.is_active = True
        user.save()
        messages.success(request, 'Your account has been activated. You can now log in.')
    else:
        messages.error(request, 'Activation link is invalid!')
    return redirect('sign-in')

# Admin Dashboard
class AdminDashboardView(TemplateView):
    template_name = 'users/admin_dashboard.html'

# Assign Role View
class AssignRoleView(View):
    def get(self, request, user_id):
        form = AssignRoleForm()
        return render(request, 'admin/assign_role.html', {'form': form})

    def post(self, request, user_id):
        user = get_object_or_404(User, pk=user_id)
        form = AssignRoleForm(request.POST)
        if form.is_valid():
            role = form.cleaned_data['role']
            user.groups.clear()
            user.groups.add(role)
            messages.success(request, f"Assigned role '{role.name}' to user.")
            return redirect('admin-dashboard')
        return render(request, 'users/assign_role.html', {'form': form})

# Group Creation
class CreateGroupView(FormView):
    form_class = CreateGroupForm
    template_name = 'admin/create_group.html'
    success_url = reverse_lazy('users:group-list')

    def form_valid(self, form):
        form.save()
        messages.success(self.request, "Group created successfully.")
        return super().form_valid(form)

# Group List
class GroupListView(ListView):
    template_name = 'admin/group_list.html'
    queryset = Group.objects.all()
    context_object_name = 'groups'

# Profile View
class ProfileView(LoginRequiredMixin, TemplateView):
    template_name = 'accounts/profile.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user
        context['profile_image'] = user.profile_image  
        context['name'] = user.get_full_name()
        context['email'] = user.email
        context['username'] = user.username
        context['member_since'] = user.date_joined
        context['last_login'] = user.last_login
        context['bio'] = "" 
        return context

    
    
# Edit Profile
class EditProfileView(LoginRequiredMixin, UpdateView):
    model = User
    form_class = EditProfileForm
    template_name = 'accounts/edit_profile.html'
    success_url = reverse_lazy('users:profile')

    def get_object(self):
        return self.request.user

# Change Password
class ChangePasswordReset(PasswordChangeView):
    form_class = CustomPasswordChangeForm
    template_name = 'accounts/change_password.html'
    success_url = reverse_lazy('password_change_done')

# Reset Password
class CustomPasswordResetView(PasswordResetView):
    form_class = CustomPasswordResetForm
    template_name = 'accounts/password_reset_form.html'
    success_url = reverse_lazy('password_reset_done')

# Confirm Password Reset
class CustomPasswordResetConfirmView(PasswordResetConfirmView):
    form_class = CustomPasswordResetConfirmForm
    template_name = 'accounts/password_reset_confirm.html'
    success_url = reverse_lazy('password_reset_complete')

users/templates/accounts/Profile.html
{% extends "base.html" %}
{% load event_extras %}
 {% comment %} {% load custom_filters %}  {% endcomment %}
{% block title %}Profile{% endblock title %}
{% block content %}
  <div class="bg-gray-100">
    <div class="flex min-h-screen">
      <!-- Sidebar -->
      <aside class="w-64 bg-white shadow-md">
        <div class="p-4">
          <h2 class="text-xl font-semibold text-gray-800">Menu</h2>
        </div>
        <nav class="mt-6">
          <a
            href="#"
            class="block py-2 px-4 text-gray-700 bg-gray-200 hover:bg-gray-300"
            >Profile</a
          >
          <a href="{% url 'users:edit_profile' %}" class="block py-2 px-4 text-gray-700 hover:bg-gray-200"
            >Edit Profile</a
          >
          <a href="{% url 'password_change' %}" class="block py-2 px-4 text-gray-700 hover:bg-gray-200"
            >Change Password</a
          >
        </nav>
      </aside>

      <!-- Main Content -->
      <main class="flex-1 p-8">
        <h1 class="text-3xl font-bold text-gray-800 mb-8">User Profile</h1>

        <div class="  bg-white shadow-md rounded-lg p-6">
          <div class="flex items-center mb-6">
            {% if profile_image %}
                <img src="{{ user.profile_img.url }}" ... >
            {% else %}
                <img src="/media/profile_img/default.jpg" alt="Default Image" class="w-24 h-24 rounded-full">
            {% endif %}


            <div>
              <h2 class="text-2xl font-semibold text-gray-800">{{name}}</h2>
              <p class="text-gray-600">Developer</p>
            </div>
          </div>

          <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div>
              <h3 class="text-lg font-semibold text-gray-700 mb-2">
                Personal Information
              </h3>
              <p class="text-gray-600">
                <span class="font-medium">Email:</span> {{ email }}
              </p>
              <p class="text-gray-600">
                <span class="font-medium">Username:</span> {{ username }}
              </p>
              <p class="text-gray-600">
                <span class="font-medium">Location:</span> New York, USA
              </p>
            </div>
            <div>
              <h3 class="text-lg font-semibold text-gray-700 mb-2">
                Account Information
              </h3>
              <p class="text-gray-600">
                <span class="font-medium">Member Since:</span> {{member_since|humanized_date}}
              </p>
              <p class="text-gray-600">
                <span class="font-medium">Last Login:</span> {{user.last_login|humanized_date}}
              </p>
            </div>
          </div>

          <div class="mt-6">
            <h3 class="text-lg font-semibold text-gray-700 mb-2">Bio</h3>
            <p class="text-gray-600">
             {{bio}}
            </p>
          </div>
        </div>
      </main>
    </div>
  </div>
  {% endblock content %}

users/templates/accounts/edit_profile.html
{% extends "base.html" %}
{% block title %}Edit Profile{% endblock title %}

{% block content %}
<div class="max-w-md mx-auto mt-10 bg-white p-6 rounded shadow">
  <h1 class="text-2xl font-bold mb-6">Edit Profile</h1>

  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.non_field_errors }}
    
    <div class="mb-4">
      <label for="id_username" class="block font-semibold mb-1">Username</label>
      {{ form.username.errors }}
      {{ form.username }}
    </div>

    <div class="mb-4">
      <label for="id_email" class="block font-semibold mb-1">Email</label>
      {{ form.email.errors }}
      {{ form.email }}
    </div>

    <div class="mb-4">
      <label for="id_phone" class="block font-semibold mb-1">Phone</label>
      {{ form.phone.errors }}
      {{ form.phone }}
    </div>

    <div class="mb-4">
      <label for="id_profile_image" class="block font-semibold mb-1">Profile Image</label>
      {{ form.profile_image.errors }}
      {{ form.profile_image }}
      {% if user.profile_image %}
        <img src="{{ user.profile_image.url }}" alt="Current profile image" class="mt-2 w-24 h-24 rounded-full object-cover"/>
      {% endif %}
    </div>

    <button type="submit" class="bg-blue-600 text-white px-4 py-2 rounded hover:bg-blue-700">
      Save Changes
    </button>
  </form>
</div>
{% endblock content %}

users/templates/accounts/password_change.html
{% extends "base.html" %}
{% block content %}
    <div class='mx-auto w-1/2 my-9'>
        {% if messages %}
            {% for message in messages %}
                <div class="px-2 py-1 {% if message.tags == 'success' %}bg-green-500{% endif %} ">{{message}}</div>
            {% endfor %}
        {% endif %}
        <form method='POST'>
            {% csrf_token %}
            {{ form }}
            <button class='bg-blue-500 px-2 py-1 rounded text-white mt-3' type="submit">Change Password</button>
        </form>
    </div>
{% endblock content %}

users/templates/accounts/password_reset_confirm.html
<h1>Password Changed Successfully</h1>
<p>Please Back to <a href="{% url 'dashboard' %}">Dashboard</a></p>

users/templates/accounts/update_profile.html
{% extends "base.html" %}
{% block content %}
    <div class='mx-auto w-1/2 my-9'>
        {% if messages %}
            {% for message in messages %}
                <div class="px-2 py-1 {% if message.tags == 'success' %}bg-green-500{% endif %} ">{{message}}</div>
            {% endfor %}
        {% endif %}
        <form method='POST' enctype='multipart/form-data'>
            {% csrf_token %}
            {{ form }}
            <button class='bg-blue-500 px-2 py-1 rounded text-white mt-3' type="submit">Update Profile</button>
        </form>
    </div>
{% endblock content %}