event_management/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
from core.views import home,no_permission
from events.views import EventListView
from django.views.generic import TemplateView 
from debug_toolbar.toolbar import  debug_toolbar_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name="home"),
    # path("cores/", include("core.urls")),
    path("events/", include("events.urls")),
    path('', EventListView.as_view(), name='home'),
    path("users/", include("users.urls",namespace="users")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('no-permission/', TemplateView.as_view(template_name="no_permission.html"), name='no-permission'),
]+ debug_toolbar_urls()
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views
from users.views import (
    SignUpView, CustomLoginView, SignOutView, activate_user,
    AdminDashboardView, AssignRoleView, CreateGroupView,
    GroupListView, ProfileView, EditProfileView,
    ChangePasswordReset, CustomPasswordResetView,
    CustomPasswordResetConfirmView,
)
app_name = 'users'
urlpatterns = [
    path('sign-up/', SignUpView.as_view(), name='sign-up'),
    path('sign-in/', CustomLoginView.as_view(), name='sign-in'),
    path('sign-out/', SignOutView.as_view(), name='sign-out'),

    # Account activation URL with user_id and token parameters
    path('activate/<int:user_id>/<str:token>/', activate_user, name='activate-user'),

    # Admin dashboard and management URLs
    path('dashboard/', AdminDashboardView.as_view(), name='admin_dashboard'),
    path('assign-role/<int:user_id>/', AssignRoleView.as_view(), name='assign-role'),
    path('create-group/', CreateGroupView.as_view(), name='create-group'),
    path('group-list/', GroupListView.as_view(), name='group-list'),

    # User profile URLs
    path('profile/', ProfileView.as_view(), name='profile'),
    path('edit-profile/', EditProfileView.as_view(), name='edit_profile'),

    # Password management
    path('password/change/', ChangePasswordReset.as_view(), name='password_change'),
    path('password/reset/', CustomPasswordResetView.as_view(), name='password_reset'),
    path('password/reset/confirm/<uidb64>/<token>/', CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
]

core/models.py
from django.db import models

# Create your models here.

core/views.py
from django.shortcuts import render


# Create your views here.
def home(request):
    return render(request, 'home.html')
def all_events(request):
    return render(request, 'all-events.html')
  
def no_permission(request):
    return render(request, 'no_permission.html')  

core/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}{% endblock title %}</title>
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&family=Noto+Sans+Bengali:wght@100..900&display=swap"
      rel="stylesheet"
    />
    <link rel="stylesheet" href="{% static 'css/output.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/daisyui@5" rel="stylesheet" type="text/css" />
    <script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script>
    <style>
      body {
        font-family: "Inter", sans-serif;
      }
    </style>
  </head>
  <body class="font-sans bg-blue-100">
    {% if request.user.is_authenticated %}
        {% include "logged_nav.html" %}
    {% else %}
        {% include "non_logged_nav.html" %}
    {% endif %}
    <main>
      {% block content %}
      
      {% endblock content %}
    </main>

   


    
{% comment %} <footer class="footer sm:footer-horizontal bg-blue-100 text-base-content p-10 font-bold">
  <aside>
    <svg
      width="50"
      height="50"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      fill-rule="evenodd"
      clip-rule="evenodd"
      class="fill-current">
      <path
        d="M22.672 15.226l-2.432.811.841 2.515c.33 1.019-.209 2.127-1.23 2.456-1.15.325-2.148-.321-2.463-1.226l-.84-2.518-5.013 1.677.84 2.517c.391 1.203-.434 2.542-1.831 2.542-.88 0-1.601-.564-1.86-1.314l-.842-2.516-2.431.809c-1.135.328-2.145-.317-2.463-1.229-.329-1.018.211-2.127 1.231-2.456l2.432-.809-1.621-4.823-2.432.808c-1.355.384-2.558-.59-2.558-1.839 0-.817.509-1.582 1.327-1.846l2.433-.809-.842-2.515c-.33-1.02.211-2.129 1.232-2.458 1.02-.329 2.13.209 2.461 1.229l.842 2.515 5.011-1.677-.839-2.517c-.403-1.238.484-2.553 1.843-2.553.819 0 1.585.509 1.85 1.326l.841 2.517 2.431-.81c1.02-.33 2.131.211 2.461 1.229.332 1.018-.21 2.126-1.23 2.456l-2.433.809 1.622 4.823 2.433-.809c1.242-.401 2.557.484 2.557 1.838 0 .819-.51 1.583-1.328 1.847m-8.992-6.428l-5.01 1.675 1.619 4.828 5.011-1.674-1.62-4.829z"></path>
    </svg>
    <p class='font-samibold'>
      ACME Industries Ltd.
      <br />
      Providing reliable tech since 1992
    </p>
  </aside>
  <nav>
    <h6 class="footer-title text-xl">Services</h6>
    <a class="link link-hover">Branding</a>
    <a class="link link-hover">Design</a>
    <a class="link link-hover">Marketing</a>
    <a class="link link-hover">Advertisement</a>
  </nav>
  <nav>
    <h6 class="footer-title text-xl">Company</h6>
    <a class="link link-hover">About us</a>
    <a class="link link-hover">Contact</a>
    <a class="link link-hover">Jobs</a>
    <a class="link link-hover">Press kit</a>
  </nav>
  <nav>
    <h6 class="footer-title text-xl">Legal</h6>
    <a class="link link-hover">Terms of use</a>
    <a class="link link-hover">Privacy policy</a>
    <a class="link link-hover">Cookie policy</a>
  </nav>


  <form>
    <h6 class="footer-title text-xl">Newsletter</h6>
    <fieldset class="w-80">
      <label>Enter your email address</label>
      <div class="join">
        <input
          type="text"
          placeholder="username@site.com"
          class="input input-bordered join-item" />
        <button class="btn btn-primary join-item">Subscribe</button>
      </div>
    </fieldset>
  </form>
</footer> {% endcomment %}

    <script>
        document
          .getElementById("menu-toggle")
          .addEventListener("click", function () {
            document.getElementById("mobile-menu").classList.toggle("hidden");
          });
  
        document
          .getElementById("user-menu-button")
          .addEventListener("click", function () {
            document.getElementById("user-menu").classList.toggle("hidden");
          });
  
        // Close the dropdown when clicking outside
        window.addEventListener("click", function (e) {
          if (!document.getElementById("user-menu-button").contains(e.target)) {
            document.getElementById("user-menu").classList.add("hidden");
          }
        });
      </script>
  </body>
</html>

core/templates/home.html
{% extends "base.html" %}
<!-- Hero Section -->
{% comment %} <section class="bg-blue-600 text-white py-32 md:py-40">
  <div class="container mx-auto px-6 text-center">
    <h1 class="text-4xl md:text-5xl font-bold mb-6">
      Organise Events Seamlessly with EventSite
    </h1>
    <p class="text-xl mb-12">
      Simplify planning, coordination, and management with our all-in-one event solution
    </p>
    <a
      href="#"
      class="bg-white text-blue-600 px-8 py-4 rounded-md font-semibold text-lg hover:bg-gray-100 transition duration-300"
    >
      Plan Your First Event
    </a>
  </div>
</section> {% endcomment %}
  {% comment %} <div class="relative w-full">
      
      <!--  Navbar overlayed on banner -->
      <div class="absolute top-0 left-0 w-full z-50  bg-opacity-40 ">
        <div class="container mx-auto">
          {% include 'events/partials/navbar.html' %}
        </div>
      </div>

      <!--  Banner image -->
      <img src="{% static 'images/banner-2.jpg' %}" alt="Banner" class="w-full h-[200px] object-cover" />
    </div>

<!-- Features Section --> {% endcomment %}
 {% comment %} {% comment %} {% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>{% block title %}Event Site{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href="https://cdn.jsdelivr.net/npm/daisyui@5" rel="stylesheet" type="text/css" />
    <script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script>
    <link href="https://cdn.jsdelivr.net/npm/daisyui@5/themes.css" rel="stylesheet" type="text/css" />
   
  </head>

  <body class="bg-base-100 mx-auto my-auto">
    {% include 'events/partials/navbar.html' %}

    {% comment %} {% block content %} {% endcomment %}
      <!-- Default content shown on home page -->

      {% comment %} <div class="carousel w-full">
        <div id="item1" class="carousel-item w-full">
          <img
            src=""
            class="w-full"
          />
        </div>
      </div>

      <div>
        <h1 class="text-center font-bold text-3xl p-4">Upcoming Events</h1>

        <div class="container mx-auto p-6">
          <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-6">
            {% for event in events %}
              {% include 'events/partials/event_card.html' %}
            {% empty %}
              <p>All Events Available.</p>
            {% endfor %}
          </div>
           <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-6"> {% endcomment %}
      {% comment %} {% for event in events %} {% endcomment %}
      {% comment %} <div class="card bg-white shadow-md rounded-xl overflow-hidden">
        {% if event.image %}
        <img src="{{ event.image.url }}" alt="{{ event.title }}" class="h-48 w-full object-cover">
        {% endif %}
        <div class="p-4">
          <h2 class="text-xl font-semibold">Event Tittle:{{ event.title }}</h2>
          <p class="text-gray-600 text-sm">Description:{{ event.description|truncatechars:100 }}</p>
          <p class="text-gray-500 text-sm mt-2">Date: {{ event.date }}</p>
        </div>
      </div>
      {% comment %} {% empty %} {% endcomment %}

          {% comment %} <div class="mt-6 text-center">
            <a href="{% url 'all_event' %}" class="btn btn-primary">See All Events</a>
          </div>
        </div>
      </div> {% endcomment %}
    {% comment %} {% endblock %} {% endcomment %}
{% comment %} 
    {% include 'events/partials/footer.html' %}
  </body>
{% comment %} </html> {% endcomment %} 



{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
  
  <head>
    <meta charset="UTF-8" />
    <title>Event Site</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href="https://cdn.jsdelivr.net/npm/daisyui@5" rel="stylesheet" type="text/css" />
    <script src="https://cdn.tailwindcss.com"></script>
  </head>

  <body class="bg-base-100">

    <!--  Banner section with navbar on top -->
    <div class="relative w-full">
      
      <!--  Navbar overlayed on banner -->
      <div class="absolute top-0 left-0 w-full z-50  bg-opacity-40 ">
        <div class="container mx-auto">
          {% include 'events/partials/navbar.html' %}
        </div>
      </div>

      <!--  Banner image -->
      <img src="{% static 'images/banner-2.jpg' %}" alt="Banner" class="w-full h-[400px] object-cover" />
    </div>

    <!-- Events Section -->
    <div class="mt-10">
      <h1 class="text-center font-bold text-3xl ">Upcoming Events</h1>
      
      <div class="container mx-auto p-6">
        <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-6">
          {% for event in events %} 
              {% include 'events/partials/event_card.html' %}
           {% empty %} 
          </div>
          <div class="mt-10 text-center">
             <a href="{% url 'event-list' %}" class="btn btn-primary">See All Events</a>  
           
          </div>
        </div>
        {% endfor %}
      </div>

<!-- Call to Action -->
<section class="py-24 md:py-32 bg-blue-100">
        <div class="container mx-auto px-6">
          <h2 class="text-3xl font-bold text-center mb-16">
            Designed for Every Role in Event Planning
          </h2>
          <div class="grid grid-cols-1 md:grid-cols-3 gap-12">
            <!-- Organizer Card -->
            <div class="bg-white rounded-lg shadow-md p-8">
              <h3 class="text-2xl font-semibold mb-6">Organizer</h3>
              <ul class="list-disc list-inside text-gray-600 space-y-3">
                <li>Create event details</li>
                <li>Assign  coordinate teams</li>
                <li>Send invites and manage Groups</li>
                <li>Track event timeline </li>
              </ul>
            </div>
            <!-- Vendor Card -->
            <div class="bg-white rounded-lg shadow-md p-8">
              <h3 class="text-2xl font-semibold mb-6">Vendor</h3>
              <ul class="list-disc list-inside text-gray-600 space-y-3">
                <li>Receive and confirm event requests</li>
                <li>Submit quotes and invoices</li>
                <li>Communicate with event organizers</li>
                <li>Update delivery </li>
              </ul>
            </div>
            <!-- Participant Card -->
            <div class="bg-white rounded-lg shadow-md p-8">
              <h3 class="text-2xl font-semibold mb-6">Participant</h3>
              <ul class="list-disc list-inside text-gray-600 space-y-3">
                <li>View upcoming events and details</li>
                <li>Submit Groups and feedback</li>
                <li>Access event schedule and venue info</li>
                <li>Engage with speakers and other guests</li>
              </ul>
            </div>
          </div>
        </div>
</section>
<!-- Call to Action -->
<section class="bg-gray-200 py-24 md:py-32">
  <div class="container mx-auto px-6 text-center">
    <h2 class="text-3xl font-bold mb-6">
      Ready to Elevate Your Next Event?
    </h2>
    <p class="text-xl mb-12">
      Join event professionals who trust EventSite for flawless execution
    </p>
    <a
      href="#"
      class="bg-blue-500 text-white px-8 py-4 rounded-md font-semibold text-lg hover:bg-blue-600 transition duration-300"
    >
      Get Started for Free
    </a>
  </div>
</section>
{% include 'events/partials/footer.html' %}
{% endblock %}
 </body>
</html>
         
           
           
      



    
 

core/templates/logged_nav.html
<header class="bg-white shadow-md">
  <nav class="container mx-auto px-6 py-3">
    <div class="flex justify-between items-center">
      <a href="{% url 'home' %}" class="text-xl font-bold text-gray-800">
        Event-Site
      </a>
      <div class="hidden md:flex space-x-4">
        <a href="{% url 'admin_dashboard' %}" class="text-gray-600 hover:text-gray-800">
          Dashboard
        </a>
        <a href="{% url 'event-list' %}" class="text-gray-600 hover:text-gray-800">
          Events
        </a>
        
        {% comment %} <a href="{% url 'create-group' %}" class="text-gray-600 hover:text-gray-800">
          Create Event
        </a> {% endcomment %}
      </div>
      <div class="flex items-center">
        <div class="relative">
          <button id="user-menu-button" class="flex items-center focus:outline-none">
            <img
              class="h-8 w-8 rounded-full object-cover"
              src="https://placekitten.com/100/100"
              alt="User avatar"
            />
          </button>
          <div
            id="user-menu"
            class="absolute right-0 mt-2 w-48 bg-white rounded-md shadow-lg py-1 hidden"
          >
            <a href="{% url 'organizer_dashboard' %}" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100">
              Organizer Panel
            </a>
            <a href="{% url 'users:profile' %}" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100">
              Profile
            </a>
            <form method="post" action="{% url 'users:sign-out' %}">
              {% csrf_token %}
              <button class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100">
                SignOut
              </button>
            </form>
          </div>
        </div>
        <div class="md:hidden ml-4">
          <button
            id="menu-toggle"
            class="text-gray-600 hover:text-gray-800 focus:outline-none"
          >
            <svg
              class="h-6 w-6"
              fill="none"
              stroke="currentColor"
              viewBox="0 0 24 24"
              xmlns="http://www.w3.org/2000/svg"
            >
              <path
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-width="2"
                d="M4 6h16M4 12h16m-7 6h7"
              ></path>
            </svg>
          </button>
        </div>
      </div>
    </div>

    <!-- Mobile menu -->
    <div id="mobile-menu" class="md:hidden hidden mt-4">
      <a href="{% url 'admin_dashboard' %}" class="block py-2 text-gray-600 hover:text-gray-800">
        Dashboard
      </a>
      <a href="{% url 'event-list' %}" class="block py-2 text-gray-600 hover:text-gray-800">
        Events
      </a>
      <a href="{% url 'users:group-list' %}" class="block py-2 text-gray-600 hover:text-gray-800">
        Groups
      </a>
      <a href="{% url 'users:create-group' %}" class="block py-2 text-gray-600 hover:text-gray-800">
        Create Event
      </a>
    </div>
  </nav>
</header>

core/templates/no_permission.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Event-Site</title>
</head>
<body>
    <h2>You do not have permission to access this page</h2>
</body>
</html>

core/templates/non_logged_nav.html
<header class="bg-blue-200 shadow-md">
    <nav class="container mx-auto px-6 py-3">
      <div class="flex justify-around items-center">
        <div class="text-2xl font-bold ml-6text-gray-800">EVENT-SITE</div>
        <div class="hidden md:flex space-x-4">
          <a href="{% url 'home' %}" class="text-gray-800 hover:text-blue-600 bg-blend-color">Home</a>
          <a href="{% url 'event-list' %}" class="text-gray-600 hover:text-gray-800">All-Events</a>

          <a href="{% url 'event-list' %}" class="text-gray-600 hover:text-gray-800">About</a>
          <a href="{% url 'admin_dashboard' %}" class="text-gray-600 hover:text-gray-800">Dashboard</a>
        </div>
        <div class="md:hidden">
          <button
            id="menu-toggle"
            class="text-gray-600 hover:text-gray-800 focus:outline-none"
          >
            <svg
              class="h-6 w-6"
              fill="none"
              stroke="currentColor"
              viewBox="0 0 24 24"
              xmlns="http://www.w3.org/2000/svg"
            >
              <path
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-width="2"
                d="M4 6h16M4 12h16m-7 6h7"
              ></path>
            </svg>
          </button>
        </div>
         <div class="flex gap-1">
          <a
            href="{% url 'users:sign-in' %}"
            class="hidden md:block bg-blue-500 text-white px-4 py-2 rounded-md hover:bg-blue-600 transition duration-300"
            >Sign In</a
          > 
          <a 
            href="{% url 'users:sign-up' %}"
            class="hidden md:block bg-blue-500 text-white px-4 py-2 rounded-md hover:bg-blue-600 transition duration-300"
            >Sign Up</a
          > 
        </div> 
      </div>
      <div id="mobile-menu" class="md:hidden hidden mt-4">
        <a href="{% url 'home' %}" class="text-gray-800 hover:text-blue-600">Home</a>
        <a href="{% url 'event-list' %}" class="block py-2 text-gray-600 hover:text-gray-800"
          >All-Events</a
        >
        <a href="{% url 'event-list' %}" class="block py-2 text-gray-600 hover:text-gray-800"
          >About</a
        >
        <a href="{% url 'admin_dashboard' %}" class="block py-2 text-gray-600 hover:text-gray-800"
          >Dashboard</a
        >
        <a href="#" class="block py-2 text-gray-600 hover:text-gray-800"
          >Sign In</a
        >
        <a href="#" class="block py-2 text-gray-600 hover:text-gray-800"
          >Sign Up</a
        >
      </div> 
    </nav>
  </header>